/**
 * Export helpers — PDF (jsPDF + autotable) and CSV.
 * All functions are fire-and-forget: they trigger a browser download.
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { calculateStandings } from './tournament.js';
import { downloadCSV } from './utils.js';

// ─── Brand colours ────────────────────────────────────────────────────────────
const NAVY  = [13, 28, 62];   // #0D1C3E
const ORANGE = [244, 120, 32]; // #F47820
const WHITE = [255, 255, 255];
const LIGHT = [245, 247, 250];

// ─── Shared helpers ───────────────────────────────────────────────────────────

function createDoc(landscape = false) {
  return new jsPDF({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
}

function addHeader(doc, title, subtitle = '') {
  // Navy header bar
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 18, 'F');

  doc.setTextColor(...WHITE);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('STATEDGE', 10, 8);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Sports Analytics', 10, 13);

  // Title on the right side
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  const w = doc.internal.pageSize.getWidth();
  doc.text(title, w - 10, 8, { align: 'right' });

  if (subtitle) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, w - 10, 13, { align: 'right' });
  }

  // Orange accent line
  doc.setFillColor(...ORANGE);
  doc.rect(0, 18, doc.internal.pageSize.getWidth(), 1.5, 'F');

  doc.setTextColor(0, 0, 0);
  return 25; // y position after header
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFillColor(...NAVY);
    doc.rect(0, h - 8, w, 8, 'F');
    doc.setFontSize(7);
    doc.setTextColor(...WHITE);
    doc.text(`Generated by StatEdge · ${new Date().toLocaleDateString()}`, 10, h - 3);
    doc.text(`Page ${i} of ${pageCount}`, w - 10, h - 3, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  }
}

const tableStyles = {
  headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
  alternateRowStyles: { fillColor: LIGHT },
  bodyStyles: { fontSize: 8 },
  margin: { left: 10, right: 10 },
};

// ─── Standings ────────────────────────────────────────────────────────────────

export function exportStandingsPDF(tournament) {
  const doc = createDoc();
  let y = addHeader(doc, `${tournament.name} — Standings`, [tournament.ageGroup, tournament.organizingBody].filter(Boolean).join(' · '));

  tournament.pools.forEach((pool, idx) => {
    const standings = calculateStandings(tournament, pool.id);
    if (idx > 0) y += 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...NAVY);
    doc.text(pool.name, 10, y);
    doc.setTextColor(0, 0, 0);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['#', 'Team', 'P', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts']],
      body: standings.map((s, i) => [i + 1, s.teamName, s.played, s.won, s.drawn, s.lost, s.goalsFor, s.goalsAgainst, s.goalDifference > 0 ? `+${s.goalDifference}` : s.goalDifference, s.points]),
      ...tableStyles,
    });
    y = doc.lastAutoTable.finalY + 6;
  });

  addFooter(doc);
  doc.save(`${tournament.name.replace(/\s+/g, '-')}-standings.pdf`);
}

export function exportStandingsCSV(tournament) {
  const rows = [];
  tournament.pools.forEach(pool => {
    calculateStandings(tournament, pool.id).forEach((s, i) => {
      rows.push({ pool: pool.name, position: i + 1, ...s });
    });
  });
  downloadCSV(rows, ['pool', 'position', 'teamName', 'played', 'won', 'drawn', 'lost', 'goalsFor', 'goalsAgainst', 'goalDifference', 'points'], `${tournament.name.replace(/\s+/g, '-')}-standings.csv`);
}

// ─── Fixtures ─────────────────────────────────────────────────────────────────

export function exportFixturesPDF(tournament, pool = null) {
  const doc = createDoc(true);
  const targetPools = pool ? [pool] : tournament.pools;
  const subtitle = [tournament.ageGroup, tournament.organizingBody].filter(Boolean).join(' · ');
  let y = addHeader(doc, `${tournament.name} — Fixtures`, subtitle);

  targetPools.forEach((p, idx) => {
    const fixtures = tournament.fixtures
      .filter(f => f.poolId === p.id)
      .sort((a, b) => {
        if (a.round !== b.round) return a.round - b.round;
        if (a.date && b.date) return a.date.localeCompare(b.date);
        return 0;
      });

    if (idx > 0) y += 4;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...NAVY);
    doc.text(p.name, 10, y);
    doc.setTextColor(0, 0, 0);
    y += 4;

    const roundNames = tournament.roundNames || {};

    autoTable(doc, {
      startY: y,
      head: [['Round', 'Date', 'Time', 'Venue', 'Court', 'Home', 'Score', 'Away', 'Status']],
      body: fixtures.map(f => {
        const home = tournament.teams.find(t => t.id === f.homeTeamId);
        const away = tournament.teams.find(t => t.id === f.awayTeamId);
        const roundLabel = roundNames[f.round] || `Round ${f.round}`;
        const score = f.played ? `${f.homeScore} – ${f.awayScore}` : 'vs';
        return [roundLabel, f.date || '', f.time || '', f.venue || '', f.court || '', home?.name || 'TBD', score, away?.name || 'TBD', f.played ? 'Played' : 'Scheduled'];
      }),
      ...tableStyles,
    });
    y = doc.lastAutoTable.finalY + 6;
  });

  addFooter(doc);
  doc.save(`${tournament.name.replace(/\s+/g, '-')}-fixtures.pdf`);
}

export function exportFixturesCSV(tournament, pool = null) {
  const targetPools = pool ? [pool] : tournament.pools;
  const roundNames = tournament.roundNames || {};
  const rows = [];

  targetPools.forEach(p => {
    tournament.fixtures
      .filter(f => f.poolId === p.id)
      .sort((a, b) => a.round - b.round)
      .forEach(f => {
        const home = tournament.teams.find(t => t.id === f.homeTeamId);
        const away = tournament.teams.find(t => t.id === f.awayTeamId);
        rows.push({
          pool: p.name,
          round: roundNames[f.round] || `Round ${f.round}`,
          date: f.date || '',
          time: f.time || '',
          venue: f.venue || '',
          court: f.court || '',
          homeTeam: home?.name || 'TBD',
          homeScore: f.played ? f.homeScore : '',
          awayScore: f.played ? f.awayScore : '',
          awayTeam: away?.name || 'TBD',
          played: f.played ? 'Yes' : 'No',
        });
      });
  });

  downloadCSV(rows, ['pool', 'round', 'date', 'time', 'venue', 'court', 'homeTeam', 'homeScore', 'awayScore', 'awayTeam', 'played'], `${tournament.name.replace(/\s+/g, '-')}-fixtures.csv`);
}

// ─── Players ──────────────────────────────────────────────────────────────────

export function exportPlayersPDF(tournament) {
  const doc = createDoc();
  const subtitle = [tournament.ageGroup, tournament.organizingBody].filter(Boolean).join(' · ');
  const y = addHeader(doc, `${tournament.name} — Players`, subtitle);

  const rows = tournament.players.map(p => {
    const team = tournament.teams.find(t => t.id === p.teamId);
    const goals = p.goalsScored ? Object.values(p.goalsScored).reduce((s, v) => s + v, 0) : 0;
    return [p.name || '', p.number || '', team?.name || 'Unassigned', p.position || '', goals];
  });

  autoTable(doc, {
    startY: y,
    head: [['Name', '#', 'Team', 'Position', 'Goals']],
    body: rows,
    ...tableStyles,
  });

  addFooter(doc);
  doc.save(`${tournament.name.replace(/\s+/g, '-')}-players.pdf`);
}

export function exportPlayersCSV(tournament) {
  const rows = tournament.players.map(p => {
    const team = tournament.teams.find(t => t.id === p.teamId);
    const goals = p.goalsScored ? Object.values(p.goalsScored).reduce((s, v) => s + v, 0) : 0;
    return { name: p.name || '', number: p.number || '', team: team?.name || 'Unassigned', position: p.position || '', goals };
  });
  downloadCSV(rows, ['name', 'number', 'team', 'position', 'goals'], `${tournament.name.replace(/\s+/g, '-')}-players.csv`);
}

// ─── Ranking list ─────────────────────────────────────────────────────────────

export function exportRankingListPDF(tournament, list) {
  const doc = createDoc();
  const y = addHeader(doc, `${tournament.name}`, list.name);

  const rows = list.teamIds.map((id, i) => {
    const team = tournament.teams.find(t => t.id === id);
    return [i + 1, team?.name || 'Unknown', team?.schoolName || '', team?.province || ''];
  });

  autoTable(doc, {
    startY: y,
    head: [['Rank', 'Team', 'School', 'Province']],
    body: rows,
    ...tableStyles,
  });

  addFooter(doc);
  doc.save(`${tournament.name.replace(/\s+/g, '-')}-${list.name.replace(/\s+/g, '-')}.pdf`);
}

export function exportRankingListCSV(tournament, list) {
  const rows = list.teamIds.map((id, i) => {
    const team = tournament.teams.find(t => t.id === id);
    return { rank: i + 1, team: team?.name || 'Unknown', school: team?.schoolName || '', province: team?.province || '' };
  });
  downloadCSV(rows, ['rank', 'team', 'school', 'province'], `${tournament.name.replace(/\s+/g, '-')}-${list.name.replace(/\s+/g, '-')}.csv`);
}
